language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  app: hire-up-turing
  skip_cleanup: true
  api_key:
    secure: kYTk3Arz/9x0zo8fHxqlP4H+axZbUoArS+s+JXNAErslYEikD2B+fmkdSl5gBdhKvfeY1xc1KZyCDZRXM8CE3Ls7Ix/r+D3g9dLIk7wbhol/EevKhmZbypT+O7FvJ0D5LsGYC3Hv4f4dSPKmvQ0aFQ81BNkVNSeFbR1QwZE7Yd1vYSPXZvKajetYRtsd9TEGSWx9zFeyV88jW0I7P6Wogs6VzrHPoBqLf70LYfQvCLwAXkr5vH3cLn+0fLrG17SM42pcXbbDgRn63TAiXnPxzRnnsVGnNjr0BTOjauJIeHX6gutLoG79rnyDfhOortU0XVGz5zNwTrhQNoto2TERljsI7aB2KavMQQ6MtPxfLM5bIm3Bg2Tx3nybFBXpVh9XeiZY1V8CjWsh15iFXbgaiHXQEjsR6xyppNVxNQgZXeaxegBhZYNOLHYomvIFIvQN9jNf2PMWr3hVicFKYYzY2fC7t/qZPcqYg5JPuTURI+yY3ElmmZQ4o9zj/IhsV5JeK1QNAXtxAm0JNZ5d09MO4jknez8NHW6id4zqwZY3liynAT1m3+aXH61IAdp4wzzWt0MwLxUGFA07EqJ8n3daAieqSi1tpqyNHGDXwuLq25yK+uDDkYhYaQdg0+LWjR5G4EVdWKDiOtzMA2iD6ODoetiVhFPDubJPjQvQ6GWPnB0=
